.\bin\pbrt.exe .\scenes\normTexScenes\normTexS000.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S000_0_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S000_0_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S000_0.5_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S000_0.5_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\normTexS003.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S003_0_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S003_0_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S003_0.5_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S003_0.5_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\normTexS005.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S005_0_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S005_0_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S005_0.5_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S005_0.5_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\normTexS007.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S007_0_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S007_0_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S007_0.5_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S007_0.5_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\normTexS022.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S022_0_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S022_0_0.5Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S022_0.5_0Manip.pbrt
.\bin\pbrt.exe .\scenes\normTexScenes\S022_0.5_0.5Manip.pbrt
